config/routes.rb
Chapter5::Application.routes.draw do
  get "users/new"
  match "/signup", to: 'users#new'
  match '/help', to: 'chapter5#help'
  match '/about', to: 'chapter5#about'
  match '/contact', to: 'chapter5#contact'
  root to: 'chapter5#home'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
    attr_accessible :email, :name, :password, :password_confirmation
    has_secure_password
    before_save { |user| user.email = email.downcase }
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
    #Password validates
    validates :password, presence: true, length: { minimum: 6 }
    validates :password_confirmation, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/chapter5_controller.rb
class Chapter5Controller < ApplicationController
  def home
  end
  def about
  end
  def contact
  end
  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def full_title(page_title)
        base_title= "Ruby on Rails Tutorial Sample App"
        if page_title.empty?
            base_title
        else
            "#{base_title} | #{page_title}"
        end
    end
end

app/helpers/chapter5_helper.rb
module Chapter5Helper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chapter5/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
    We are a locally owned Dunedin company with computer services
    primarily aimed at students.
</p>

app/views/chapter5/contact.html.erb
<% provide(:title, 'Contact Us') %>
<h1>Contact</h1>
<p>
    Need help with you gg computers service?
    <a href="http://ggcomputers.co.nz/contact">GGComputers Contact Page</a>
</p>

app/views/chapter5/help.html.erb
<%  provide(:title,'Help') %>
<div class="center hero-unit">
    <h1>Help Page</h1>
    <h2>
    Welcome to the Help are you lost on     the ggcomputers website
    </h2>

 </div>

<%= link_to image_tag("rails.png", alt: "Rails"), "http://rubyonrails.org"%>

app/views/chapter5/home.html.erb
<div class="center hero-unit">
    <h1>GGComputers</h1>
    
    <h2>
        This is the home page for the
        <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
        sample application
    </h2>

    <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>

</div>

<%= link_to image_tag("rails.png", alt: "Rails"), "http://rubyonrails.org"%>

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        <a href="http://railstutorial.org/">Rails Tutorial</a>
        by Michael Hartl
    </small>
    <nav>
        <ul>
            <li><%= link_to "About",    about_path %></li>
            <li><%= link_to "Contact",  contact_path %></li>
            <li><a href="http://news.railstutorial.org/">News</a></li>
        </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
        <div class="container">
            <%= link_to "sample app", root_path, id: "logo" %>
            <nav>
                <ul class="nav pull-right">
                    <li><%= link_to "Home",    root_path %></li>
                    <li><%= link_to "Help",    help_path %></li>
                    <li><%= link_to "Sign In", '#' %></li>
                </ul>
            </nav>
        </div>
    </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=full_title(yield(:title))%></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render '/layouts/shim' %>
</head>
<body>
    <%= render '/layouts/header' %>
    <div class="container">
        <%= yield %>
        <%= render '/layouts/footer' %>
        <%= debug(params) if Rails.env.development? %>
    </div>
</body>
</html>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>
<h1>Sign Up</h1>
<p>Find me in app/views/users/new.html.erb</p>